### ISSUE TITLE
Epic - error handling

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#289]
When items in a batch fail, that should be tracked.

Issues include the different kinds of failure: failure in code that can be caught with try/catch, errors during indexing or commit that cannot be caught, failure of a transaction that includes many individual records, failure due to validation issues.

The batch should continue, and in some cases the "failed" item should probably be further processed and saved, but in others rejected and tracked somewhere else safely, in a way that does not impact searches and queries.

**Comment by jmakeig** [comment]
@sammefford Copying Sam too. Failure conditions are an important part of DMSDK. Let’s make sure we’re on the same page.

**Comment by miguelrgonzalez** [comment]
I would be interesting to handle external system errors as well.
If the harmonization flow depends on a external system (i.e enrichment) I would like to be able to catalog errors as retryable (via error codes maybe?). 
Since we are already using spring-batch, I was thinking we could use Spring statefull retries http://docs.spring.io/spring-batch/reference/html/retry.html

**Comment by paxtonhare** [comment]
We pretty much do this now. How you handle errors is up to you.
